### PR TITLE
Dockerization of yamcs quickstart

### PR DESCRIPTION
**Pull request by haisamido**
Dockerization of yamcs quickstart. In the `./docker` folder, there is a `Makefile` and running `make` yields:

```
#---------------------------------------------------------------------------------- 
# Makefile                                           
#---------------------------------------------------------------------------------- 
#-targets----------------------description----------------------------------------- 
all                            run all, yamcs-build, yamcs-up (yamcs-down) and yamcs-simulator
yamcs-build                    build yamcs system
yamcs-down                     bring down yamcs system
yamcs-shell                    shell into yamcs container
yamcs-simulator                run yamcs simulator
yamcs-up                       bring up yamcs system
```

### CODE REVIEW

**Comment by fqqb** [comment]
Hi thanks for your work.

I'm good on the idea, many people seem to favour running through docker (even for development purposes). But two observations from my side for discussion:

* The base image is `maven:latest` and this seems to resolve to a Java 15 installation. However we only target Java 8 or 11. (= LTS versions). Can we use another one of the tags on that image? Preferably such that it becomes Java 11. Details: Java 15 dropped the JavaScript Nashorn engine, which leads to some features of Yamcs (e.g. algorithms) not working there.
* I tried the `make all` and was a bit surprised that it was cloning the project from GitHub again. Would it not be more useful to just map the parent directory via volume? Otherwise if you make changes locally, there's no way to try them out (?)

**Comment by haisamido** [comment]
> Hi thanks for your work.
> 
> I'm good on the idea, many people seem to favour running through docker (even for development purposes). But two observations from my side for discussion:
> 
> * The base image is `maven:latest` and this seems to resolve to a Java 15 installation. However we only target Java 8 or 11. (= LTS versions). Can we use another one of the tags on that image? Preferably such that it becomes Java 11. Details: Java 15 dropped the JavaScript Nashorn engine, which leads to some features of Yamcs (e.g. algorithms) not working there.
> * I tried the `make all` and was a bit surprised that it was cloning the project from GitHub again. Would it not be more useful to just map the parent directory via volume? Otherwise if you make changes locally, there's no way to try them out (?)

Your observations are valuable and I'll fix them.

**Comment by haisamido** [comment]
@fqqb I pushed the changes that you suggested. Let me know if they work for you or not.

**Comment by fqqb** [comment]
ty

**Comment by haisamido** [comment]
> ty

You're welcome @fqqb . Thank you for merging it.

**Pull request merged**
